### PR TITLE
Fix missing warning passing inside tableRow

### PR DESCRIPTION
**Pull request by piechot**

### CODE REVIEW

**Comment by piechot** [comment]
@julianlam , I'd appreciate if you could find 5 minutes soon to release 1.1.2 with this fix 🙏 Actually it's a follow up to 1.1.1 which fixed 4/5 of such cases.

**Review by julianlam — APPROVED** [review]

**Comment by piechot** [comment]
Hey @julianlam , thanks for quick review! Do you think it's doable to merge and release this anytime soon? Thanks in advance for your time! Hope it doesn't take too long 🤞

**Comment by corbinschwartz** [comment]
@julianlam any chance this could get merged and released?

**Comment by julianlam** [comment]
Indeed! v1.2.0, thanks!

**Pull request merged**
